# Generated by Django 4.2.17 on 2025-04-24 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254, unique=True)),
                ('business_phone', models.CharField(max_length=20)),
                ('business_address', models.TextField()),
                ('business_description', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('public_key', models.CharField(max_length=64, unique=True)),
                ('secret_key', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('settlement_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('settlement_account', models.CharField(blank=True, max_length=20, null=True)),
                ('settlement_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='number_of_retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('expired', 'Expired'), ('past_due', 'Past Due')], default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('blocked', 'Blocked')], default='low', max_length=10)),
                ('is_flagged', models.BooleanField(default=False)),
                ('rules_triggered', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='payments.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='internal', max_length=50)),
                ('method_type', models.CharField(choices=[('card', 'Card'), ('bank_account', 'Bank Account'), ('mobile_money', 'Mobile Money'), ('ussd', 'USSD')], default='card', max_length=20)),
                ('card_type', models.CharField(blank=True, max_length=20, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('exp_month', models.CharField(blank=True, max_length=2, null=True)),
                ('exp_year', models.CharField(blank=True, max_length=4, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='payments.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('velocity', 'Velocity Check'), ('amount', 'Amount Threshold'), ('location', 'Location Based'), ('device', 'Device Fingerprint'), ('pattern', 'Transaction Pattern'), ('custom', 'Custom Rule')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('risk_score', models.IntegerField(default=10)),
                ('conditions', models.TextField()),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_rules', to='payments.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='NGN', max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
        migrations.CreateModel(
            name='BlacklistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_global', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_ips', to='payments.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.merchant'),
        ),
        migrations.CreateModel(
            name='PaymentMethodStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_count', models.IntegerField(default=0)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_stats', to='payments.merchant')),
            ],
            options={
                'unique_together': {('merchant', 'date', 'payment_method', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='MerchantPaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20)),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('configuration', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_providers', to='payments.merchant')),
            ],
            options={
                'unique_together': {('merchant', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='MerchantCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('auto_convert', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='payments.merchant')),
            ],
            options={
                'unique_together': {('merchant', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='GeographicStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=2)),
                ('transaction_count', models.IntegerField(default=0)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographic_stats', to='payments.merchant')),
            ],
            options={
                'unique_together': {('merchant', 'date', 'country', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='BlacklistedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=6)),
                ('last4', models.CharField(max_length=4)),
                ('reason', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_global', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_cards', to='payments.merchant')),
            ],
            options={
                'unique_together': {('bin', 'last4', 'merchant')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_transactions', models.IntegerField(default=0)),
                ('successful_transactions', models.IntegerField(default=0)),
                ('failed_transactions', models.IntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('new_customers', models.IntegerField(default=0)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='payments.merchant')),
            ],
            options={
                'unique_together': {('merchant', 'date', 'currency')},
            },
        ),
    ]
