# Generated by Django 4.2.17 on 2025-04-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_merchant_customer_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='aml_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='compliance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('review', 'Under Review')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pci_compliant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fraudrule',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('ZAR', 'South African Rand'), ('GHS', 'Ghanaian Cedi'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('AED', 'UAE Dirham'), ('EGP', 'Egyptian Pound'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandan Franc'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('SGD', 'Singapore Dollar'), ('XOF', 'West African CFA Franc'), ('XAF', 'Central African CFA Franc')], default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('flagged', 'Flagged for Review')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MerchantCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pci_compliance_level', models.IntegerField(default=4)),
                ('pci_compliance_complete', models.BooleanField(default=False)),
                ('pci_last_verified', models.DateTimeField(blank=True, null=True)),
                ('aml_program_accepted', models.BooleanField(default=False)),
                ('aml_program_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('kyc_procedures_accepted', models.BooleanField(default=False)),
                ('kyc_procedures_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('data_protection_accepted', models.BooleanField(default=False)),
                ('data_protection_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('high_risk_category', models.BooleanField(default=False)),
                ('enhanced_due_diligence_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_info', to='payments.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_level', models.IntegerField(choices=[(0, 'Not Verified'), (1, 'Basic Verification'), (2, 'Standard Verification'), (3, 'Enhanced Verification')], default=0)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('id_card', 'National ID Card'), ('driver_license', "Driver's License"), ('voter_card', "Voter's Card")], max_length=20, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_expiry', models.DateField(blank=True, null=True)),
                ('id_country', models.CharField(blank=True, max_length=2, null=True)),
                ('address_verified', models.BooleanField(default=False)),
                ('address_verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_pep', models.BooleanField(default=False)),
                ('pep_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_info', to='payments.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('transaction', 'Transaction Check'), ('customer', 'Customer KYC Check'), ('merchant', 'Merchant Compliance Check')], max_length=20)),
                ('is_compliant', models.BooleanField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_logs', to='payments.customer')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_logs', to='payments.merchant')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_logs', to='payments.transaction')),
            ],
        ),
    ]
