# Generated by Django 4.2.17 on 2025-05-01 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_supportticket_supportticketreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_ticket', 'New Ticket'), ('ticket_reply', 'Ticket Reply'), ('status_change', 'Status Change'), ('assignment', 'Ticket Assignment'), ('escalation', 'Ticket Escalation')], max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('template_used', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payments.supportticket')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
