# Generated by Django 4.2.17 on 2025-05-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_supportticketnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='transaction_fee_percentage',
        ),
        migrations.AddField(
            model_name='merchant',
            name='international_transaction_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=3.9, max_digits=5),
        ),
        migrations.AddField(
            model_name='merchant',
            name='international_transaction_flat_fee',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='merchant',
            name='local_transaction_fee_cap',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
        migrations.AddField(
            model_name='merchant',
            name='local_transaction_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='merchant',
            name='local_transaction_fee_waiver_threshold',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=10),
        ),
        migrations.AddField(
            model_name='merchant',
            name='local_transaction_flat_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='merchant',
            name='settlement_currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='NGN', max_length=3),
        ),
    ]
