# Generated by Django 4.2.17 on 2025-05-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_merchant_transaction_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
