name: hamsukypay
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: your-github-username/hamsukypay
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  buildpacks:
    - name: python
  envs:
    - key: DJANGO_SETTINGS_MODULE
      value: hamsukypay.settings
    - key: DEBUG
      value: "False"
    - key: SECRET_KEY
      scope: RUN_TIME
      value: ${SECRET_KEY}
    - key: ALLOWED_HOSTS
      value: ${APP_DOMAIN},*.ondigitalocean.app
    - key: PRODUCTION
      value: "True"
    - key: DATABASE_URL
      scope: RUN_TIME
      value: ${DATABASE_URL}
    - key: EMAIL_HOST
      scope: RUN_TIME
      value: ${EMAIL_HOST}
    - key: EMAIL_PORT
      scope: RUN_TIME
      value: ${EMAIL_PORT}
    - key: EMAIL_HOST_USER
      scope: RUN_TIME
      value: ${EMAIL_HOST_USER}
    - key: EMAIL_HOST_PASSWORD
      scope: RUN_TIME
      value: ${EMAIL_HOST_PASSWORD}
    - key: DEFAULT_FROM_EMAIL
      value: "noreply@hamsukypay.com"
  routes:
    - path: /
databases:
- name: hamsukypay-db
  engine: PG
  version: "14"
  production: true
  db_name: hamsukypay
  db_user: hamsukypay